version: "3.9"

# Building upon the docker-compose.yml file to make changes for a production environment.
# Need to give the Dockerfile the NODE_ENV argument to determine which dependencies that should be installed.
services: 
  producer:
    build:
      args:
        NODE_ENV: production
    environment: 
      - NODE_ENV=production
    command: npm run prod

  consumer:
    build:
      args:
        NODE_ENV: production
    environment: 
      - NODE_ENV=production
    command: npm run prod